### ISSUE TITLE
When user chooses a different category, have the map automatically update with the metric at the top of the metric list.

### ISSUE THREAD

**Issue by jbvogler** [ncsu-cga/HumanFootprint#14]
For example, if I switch to Impervious Surface category, map will automatically display Hectares of Impervious surface in 2010 variable.

**Comment by mshukuno** [comment]
Please provide me the default field for each category.

**Comment by jbvogler** [comment]
Default field is metric at the top of the metric list for each category.

**Comment by jbvogler** [comment]
Default fields by category:
Housing Density --> HU2010
Impervious Surface --> IMPHA10
Land-Use Efficiency --> LUEFF0010
Per Capita Consumption --> IMPHAPP10
Population --> POP2010

**Comment by mshukuno** [comment]
I tested briefly so I would very much appreciate if you could check the function.  Thanks!

**Comment by jbvogler** [comment]
Works great! Just one small final tweak: Please change the default field for Housing Density category to "HD2010".  That was my mistake...should be HD2010, not HU2010.  After that change, it's ready to be merged.  Thanks so much!
