### ISSUE TITLE
Put "III. Select category" text instruction inside the dropdown box.

### ISSUE THREAD

**Issue by jbvogler** [ncsu-cga/HumanFootprint#6]

**Comment by mshukuno** [comment]
There should be a category dropdown?

**Comment by jbvogler** [comment]
Yes, after the county data loads, the variables/metrics are categorized by "Housing Density, Impervious Surface, Land-Use Efficiency, Per-Capita Consumption, Population" (these are the category names in the new censusblockinfo.js file.

**Comment by mshukuno** [comment]
The current setting is always something is selected.  Does it mean no default setting?

**Comment by jbvogler** [comment]
Oh, right!  I get it now.   Please then display "III. Select category" above the dropdown box, and keep "Per Capita Consumption" as the default category, and IMPHAPP10 as the default metric for that category.
