### ISSUE TITLE
Regarding the map legend, could the field name be replaced (or appended) with the units of the metric?

### ISSUE THREAD

**Issue by jbvogler** [ncsu-cga/HumanFootprint#9]
for example, HD2000 would be replaced with "Units/hectare in 2000"

**Comment by mshukuno** [comment]
The Legend Widget takes field alias and there is no API to change.  We have two choices, 1) modify field alias" (easiest) and 2) overwriting an HTML element - in that case, I will need to have a "case" for each field alias like if HU2010, query a Legend Widget HTML element and relace with XXX (additional coding).

For now, I changed the field alias for some fields.

**Comment by jbvogler** [comment]
Thanks!, which file do I edit to add or modify field aliases.

**Comment by mshukuno** [comment]
You will need to modify the feature layer published on ArcGIS Online.  I created a Human Footprint group on AGOL and shared the layers with a group.  Add the web "Cont_US_Block_Groups_2010_2000" in your map and modify the alias and overwrite the published layer or provide me a text file or spreadsheet for the field and alias by email.

**Comment by jbvogler** [comment]
I will update the field descriptions excel spreadsheet and send to you via email.

**Comment by mshukuno** [comment]
Done
